oauthagent:
  clientID: ${CLIENT_ID:spa-client}
  clientSecret: ${CLIENT_SECRET:Password1}
  redirectUri: ${REDIRECT_URI:http://www.example.local/}
  postLogoutRedirectURI: ${POST_LOGOUT_REDIRECT_URI:http://www.example.local/}
  scope: ${SCOPE:openid profile}

  encKey: ${COOKIE_ENCRYPTION_KEY:4e4636356d65563e4c73233847503e3b21436e6f7629724950526f4b5e2e4e50}
  cookieNamePrefix: ${COOKIE_NAME_PREFIX:example}
  endpointsPrefix: 'oauth-agent'
  cookieSerializeOptions:
    httpOnly: true
    sameSite: true
    secure: false
    domain: ${COOKIE_DOMAIN:api.example.local}
    path: '/'

  trustedWebOrigins:
  - ${TRUSTED_WEB_ORIGIN:http://www.example.local}
  corsEnabled: ${CORS_ENABLED:true}
  issuer: ${ISSUER:http://login.example.local:8443/oauth/v2/oauth-anonymous}
  jwksUri: ${JWKS_URI:http://login.example.local:8443/oauth/v2/oauth-anonymous/jwks}
  authorizeEndpoint: ${AUTHORIZE_ENDPOINT:http://login.example.local:8443/oauth/v2/oauth-authorize}
  logoutEndpoint: ${LOGOUT_ENDPOINT:http://login.example.local:8443/oauth/v2/oauth-session/logout}
  tokenEndpoint: ${TOKEN_ENDPOINT:http://login.example.local:8443/oauth/v2/oauth-token}
  userInfoEndpoint: ${USERINFO_ENDPOINT:http://login.example.local:8443/oauth/v2/oauth-userinfo}

server:
  port: ${PORT:8080}
  ssl:
    enabled: ${USE_SSL:false}
    key-store: ${SERVER_CERT_P12_PATH:}
    key-store-password: ${SERVER_CERT_P12_PASSWORD:}